  parameters:
    envName: '' 

  variables:
    WEB_PROJECT_NAME: "SmartRestaurant.Client.Web"
    ARTIFACTS_OUTPUT_PATH: "/home/ubuntu/test-SmartRestaurant"
  jobs:
  - deployment: Deploy
    displayName: deploy Web App
    timeoutInMinutes: 5
    environment: ${{ parameters.envName }}
    strategy:
      runOnce:
        deploy:
          steps:
           - checkout: none
           - script: |
               mkdir -p $ARTIFACTS_OUTPUT_PATH
               rm -rf $ARTIFACTS_OUTPUT_PATH/*
               cd "$WEB_PROJECT_NAME"
               dotnet publish --no-restore -c Release --output=$ARTIFACTS_OUTPUT_PATH
               sudo systemctl restart SmartRestaurant.service