  parameters:
    WebProjectName: 'src/Presentation/SmartRestaurant.Web/'
    TestProjectName: 'test'
  
  jobs:
  - job: Build_the_Website
    steps:
      - script: |
         cd ${{ parameters.WebProjectName }}
         dotnet clean
         dotnet restore
        displayName: Restore Common Packages
      - script: |
         cd "src/Libraries/SmartRestaurant.Application/"
         dotnet add package DataTables.AspNetCore.Mvc
        displayName: Add AspNetCore.Mvc Packages
      - script: |
          cd ${{ parameters.WebProjectName }}
          dotnet build --no-restore
        displayName: Build the Website
#      - task: VSTest@2
#        inputs:
#            testSelector: 'testAssemblies'
#            testAssemblyVer2: |
#              **\*test*.dll
#              !**\*TestAdapter.dll
#              !**\obj\**
#            searchFolder: '$(System.DefaultWorkingDirectory)'
#            runTestsInIsolation: true
#            codeCoverageEnabled: true
      
  - job: Database_Migration
    steps:
     - checkout: none
     - script: |
         cd ${{ parameters.WebProjectName }}
         dotnet ef database update --context:SmartRestaurantDbContext
         dotnet ef database update --context:SmartRestaurantIdentityDbContext
       displayName: Database Initialization
    dependsOn: Build_the_Website
    condition: succeeded()
