
  jobs:
#  - job: Crunch_Scan
#    steps:
#      - task: APIContractSecurityAudit@2
#        inputs:
#          apiToken: '$(42C_API_TOKEN)'
#        displayName: Crunch API Security Scanning

   - job: Snyk_Scan
     dependsOn: []
     steps:
      - task: SnykSecurityScan@0
        inputs:
          serviceConnectionEndpoint: 'Snyk_connect'
          testType: 'app'
          targetFile: 'SmartRestaurant.sln'
          monitorOnBuild: false
          failOnIssues: false
          projectName: 'Smart Restaurant'
          organization: 'g22rie'
        displayName: Snyk Sourrce Code Security Scanning