
 jobs:
  - job: Tests
    steps:
      - task: VSTest@2
        inputs:
            testAssemblyVer2: |
              **\$(BuildConfiguration)\*test*.dll
              !**\*TestAdapter.dll
              !**\obj\**
            platform: '$(BuildPlatform)'
            configuration: '$(BuildConfiguration)'
            runTestsInIsolation: true
            codeCoverageEnabled: true
        displayName: Run tests