
 jobs:
  - job: Tests
    steps:
    - task: DotNetCoreCLI@2
      inputs:
        command: 'test'
        projects: '$(Build.SourcesDirectory)\tests\SmartRestaurant.Application.Tests' 
        arguments: '--no-build --configuration Debug'
        testRunTitle: 'Unit Tests'
        publishTestResults: true
      displayName: Run tests