  parameters:
    WebProjectName: 'SmartRestaurant.Client.Web'
  
  jobs:
  - job:
    steps:
      - checkout: none
      - task: SonarQubePrepare@4
        inputs:
          SonarQube: 'TestSonar'
          scannerMode: 'MSBuild'
          projectKey: 'test01'
          projectName: 'TestEADNproject'
        displayName: Prepare SonarQube
  - job: Restore_Nuget_Packages
    timeoutInMinutes: 5
    steps:
     - script: |
         cd ${{ parameters.WebProjectName }}
         dotnet clean
         dotnet restore
       displayName: Restore Common Packages
     - script: |
         cd "SmartRestaurant.Application"
         dotnet add package DataTables.AspNetCore.Mvc
       displayName: Add AspNetCore.Mvc Package
  - job: Build_the_Website
    dependsOn: Restore_Nuget_Packages
    condition: succeeded()
    timeoutInMinutes: 5
    steps:
     - checkout: none
     - script: |
          cd ${{ parameters.WebProjectName }}
          dotnet build --no-restore
       displayName: Build the Website
  - job: SonarQubeAnalyze
    steps:
    - checkout: none
    - task: SonarQubeAnalyze@4
      displayName: SonarQube Analyze Code
  - job: SonarQubePublish
    steps:
    - checkout: none
    - task: SonarQubePublish@4
      inputs:
        pollingTimeoutSec: '300'
      displayName: SonarQube Publish Report
  - job: Database_Migration
    steps:
     - checkout: none
     - script: |
         cd ${{ parameters.WebProjectName }}
         dotnet ef database update --context:SmartRestaurantDbContext
         dotnet ef database update --context:SmartRestaurantIdentityDbContext
    dependsOn: Build_the_Website
    condition: succeeded()
