variables:
  buildConfiguration: 'Release'

jobs:
  - job: Build and Test on Windows Environment 
    steps:
    - task: DotNetCoreCLI@2
      inputs:
        command: 'restore'
        projects: 'src/Presentation/SmartRestaurant.Web/*.csproj'
      displayName: 'dotnet restore $(buildConfiguration)'

    - task: DotNetCoreCLI@2
      inputs:
        command: 'build'
        projects: 'src/Presentation/SmartRestaurant.Web/*.csproj'
        arguments: '--configuration $(buildConfiguration)'
      displayName: 'dotnet build $(buildConfiguration)'

    - task: DotNetCoreCLI@2
      inputs:
       command: test
       projects: '**/*Tests/*.csproj'
       arguments: '--configuration $(buildConfiguration)'
