  parameters:
    WebProjectName: 'src/Presentation/SmartRestaurant.API/'
    TestProjectFolder: 'tests'
  
  jobs:
  - job: Build_the_API
    steps:
      - script: |
         cp devops/$(Agent.Name).json ${{ parameters.WebProjectName }}/appsettings.json
         cd ${{ parameters.WebProjectName }}
         dotnet clean SmartRestaurant.API.csproj
         dotnet restore SmartRestaurant.API.csproj
        displayName: Restore Common Packages
      - script: |
         cp devops/$(Agent.Name).json src/Libraries/SmartRestaurant.Application/appsettings.json
         cp devops/$(Agent.Name).json src/Libraries/SmartRestaurant.Infrastructure/appsettings.json
         cd "src/Libraries/SmartRestaurant.Application/"
         dotnet add package DataTables.AspNetCore.Mvc
        displayName: Add AspNetCore.Mvc Packages
      - script: |
          cd ${{ parameters.WebProjectName }}
          dotnet build --no-restore SmartRestaurant.API.csproj
        displayName: Build
      
      
  - job: Database_Migration
    steps:
     - checkout: none
     - script: |
         cd ${{ parameters.WebProjectName }}
         dotnet ef database update --context:ApplicationDbContext
         dotnet ef database update --context:IdentityContext
       displayName: Database Initialization
    dependsOn: Build_the_API
    condition: succeeded()
