
 jobs:
  - job: Tests
    steps:
      - task: VSTest@2
        inputs:
            testAssemblyVer2: |
              **\*.Test.dll
              !**\*TestAdapter.dll
              !**\obj\**
            searchFolder: '$(Build.SourcesDirectory)\tests' 
            platform: '$(BuildPlatform)'
            configuration: '$(BuildConfiguration)'
            runTestsInIsolation: true
            codeCoverageEnabled: true
        displayName: Run tests