parameters:
  buildConfiguration: 'Release'

jobs:
  - job: Tests_on_Wind
    steps:
    - task: UseDotNet@2
      inputs:
        version: '3.1.x'
      displayName: 'Use dotnet core 3.1.x'

    - task: DotNetCoreCLI@2
      inputs:
        command: 'restore'
        projects: 'src/Presentation/SmartRestaurant.API/*.csproj'
      displayName: 'dotnet restore ${{ parameters.buildConfiguration }}'

    - task: DotNetCoreCLI@2
      inputs:
        command: 'build'
        projects: 'src/Presentation/SmartRestaurant.API/*.csproj'
        arguments: '--configuration ${{ parameters.buildConfiguration }}'
      displayName: 'dotnet build ${{ parameters.buildConfiguration }}'

    - task: VisualStudioTestPlatformInstaller@1
      inputs:
        packageFeedSelector: 'nugetOrg'
        versionSelector: 'latestStable'
      displayName: 'install SQL tools'

#    - task: DotNetCoreCLI@2
#      inputs:
#        command: test
#        projects: '**/*Tests/*.csproj'
#        arguments: '--configuration ${{ parameters.buildConfiguration }} --collect "Code Coverage"'
#      displayName: 'dotnet tests ${{ parameters.buildConfiguration }}'

    - task: VSTest@2
      inputs:
        testSelector: 'testAssemblies' # Options: testAssemblies, testPlan, testRun
        testAssemblyVer2: | # Required when testSelector == TestAssemblies
          **\*.Test.dll
        searchFolder: '**/*Tests/*' 
        codeCoverageEnabled: true
      displayName: 'dotnet tests ${{ parameters.buildConfiguration }}'
      
