  parameters:
    envName: '' 
    ArtifactsOutputPath: '/home/ubuntu/test-SmartRestaurant'
    WebProjectName: 'SmartRestaurant.Client.Web'

  jobs:
  - deployment: Deploy
    displayName: deploy Web App
    timeoutInMinutes: 5
    environment: ${{ parameters.envName }}
    strategy:
      runOnce:
        deploy:
          steps:
           - checkout: none
           - script: |
               mkdir -p ${{ ArtifactsOutputPath }}
               rm -rf ${{ ArtifactsOutputPath }}
               cd ${{ WebProjectName }}
               dotnet publish --no-restore -c Release --output=${{ ArtifactsOutputPath }}
               sudo systemctl restart SmartRestaurant.service