  parameters:
    WebProjectName: 'src/Presentation/SmartRestaurant.Web/'
    TestProjectFolder: 'tests'
  
  jobs:
  - job: Build_the_Website
    steps:
      - script: |
         cp devops/appsettings.json ${{ parameters.WebProjectName }}
         cd ${{ parameters.WebProjectName }}
         dotnet clean
         dotnet restore
        displayName: Restore Common Packages
      - script: |
         cp devops/appsettings.json src/Libraries/SmartRestaurant.Application/
         cp devops/appsettings.json src/Libraries/SmartRestaurant.Infrastructure/
         cd "src/Libraries/SmartRestaurant.Application/"
         dotnet add package DataTables.AspNetCore.Mvc
        displayName: Add AspNetCore.Mvc Packages
      - script: |
          cd ${{ parameters.WebProjectName }}
          dotnet build --no-restore
        displayName: Build the Website
      
      
  - job: Database_Migration
    steps:
     - checkout: none
     - script: |
         cd ${{ parameters.WebProjectName }}
         dotnet ef database update --context:ApplicationDbContext
         dotnet ef database update --context:IdentityDbContext
       displayName: Database Initialization
    dependsOn: Build_the_Website
    condition: succeeded()
