  parameters:
    AngularProjectName: 'src/Presentation/SmartRestaurant.Web/ClientApp/'
    TestProjectName: 'test'
  
  jobs:
  - job: Build_angular_WebClient
    steps:
      - script: |
         cd ${{ parameters.AngularProjectName }}
         npm install 
        displayName: Install Angular Dependencies
      - script: |
         cd ${{ parameters.AngularProjectName }}
         ng build --prod
        displayName: Build Angular WebClient
