  jobs:
  variables:
    WEB_PROJECT_NAME: "SmartRestaurant.Client.Web"
    ARTIFACTS_OUTPUT_PATH: "/home/ubuntu/test-SmartRestaurant"
  - job: Restore_Nuget_Packages
    timeoutInMinutes: 5
    steps:
     - script: |
         cd "$WEB_PROJECT_NAME"
         dotnet clean
         dotnet restore
       displayName: Restore Common Packages
     - script: |
         cd "SmartRestaurant.Application"
         dotnet add package DataTables.AspNetCore.Mvc
       displayName: Add AspNetCore.Mvc Package
  - job: Build_the_Website
    dependsOn: Restore_Nuget_Packages
    condition: succeeded()
    timeoutInMinutes: 5
    steps:
     - checkout: none
     - script: |
          cd "$WEB_PROJECT_NAME"
          dotnet build --no-restore
       displayName: Build the Website
  - job: Database_Migration
    steps:
     - checkout: none
     - script: |
         cd "$WEB_PROJECT_NAME"
         dotnet ef database update --context:SmartRestaurantDbContext
         dotnet ef database update --context:SmartRestaurantIdentityDbContext
    dependsOn: Build_the_Website
    condition: succeeded()
