  parameters:
    envName: '' 
    ArtifactsOutputPath: '/home/ubuntu/test-SmartRestaurant'
    WebProjectName: 'src/Presentation/SmartRestaurant.API/'

  jobs:
  - deployment: Deploy
    displayName: deploy Web App
    timeoutInMinutes: 5
    environment: ${{ parameters.envName }}
    strategy:
      runOnce:
        deploy:
          steps:
           - checkout: none
           - script: |
               mkdir -p ${{ parameters.ArtifactsOutputPath }}
               rm -rf ${{ parameters.ArtifactsOutputPath }}
               cd ${{ parameters.WebProjectName }}
               dotnet publish --no-restore -c Release --output=${{ parameters.ArtifactsOutputPath }} SmartRestaurant.API.csproj
               sudo systemctl restart SmartRestaurant.service