parameters:
  buildConfiguration: 'Release'

jobs:
  - job: Tests_on_Wind
    steps:
    - task: UseDotNet@2
      inputs:
        version: '3.1.x'
      displayName: 'Use dotnet core 3.1.x'

    - task: DotNetCoreCLI@2
      inputs:
        command: 'restore'
        projects: '**/*Tests/*.csproj'
      displayName: 'dotnet restore ${{ parameters.buildConfiguration }}'

    - task: DotNetCoreCLI@2
      inputs:
        command: 'build'
        projects: '**/SmartRestaurant.Application.Tests/*.csproj'
        arguments: '--configuration ${{ parameters.buildConfiguration }}'
      displayName: 'dotnet build ${{ parameters.buildConfiguration }}'

#    - task: DotNetCoreCLI@2
#      inputs:
#        command: test
#        projects:  '**/*Tests/*.csproj'
#        arguments: '--configuration ${{ parameters.buildConfiguration }} --collect "XPlat Code Coverage"'
#      displayName: 'dotnet tests ${{ parameters.buildConfiguration }}'

#    - task: PublishCodeCoverageResults@1
#      inputs:
#        codeCoverageTool: 'Cobertura'
#        summaryFileLocation: '$(Build.SourcesDirectory)/**/coverage.cobertura.xml'
#      displayName: 'Publish code coverage report'


    - task: VSTest@2
      inputs:
        testSelector: 'testAssemblies' # Options: testAssemblies, testPlan, testRun
        testAssemblyVer2: | # Required when testSelector == TestAssemblies
          **\*[Tt]est*.dll
          !**\*[Tt]estAdapter*.dll
          !**\obj\**
        searchFolder: 'tests/SmartRestaurant.Application.Tests/'
        configuration: '${{ parameters.buildConfiguration }}'
        codeCoverageEnabled: true
        otherConsoleOptions: '/Platform:x86'
        platform: 'x86|x64'
      displayName: 'dotnet tests ${{ parameters.buildConfiguration }}'
      
