  parameters:
    WebProjectName: 'src/Presentation/SmartRestaurant.Web/'
    TestProjectFolder: 'tests'
  
  jobs:
  - job: Unit Tests
    steps:
      - task: VSTest@2
        inputs:
            testSelector: 'testAssemblies'
            testAssemblyVer2: |
              **\*test*.dll
              !**\*TestAdapter.dll
              !**\obj\**
            searchFolder: "${{ parameters.TestProjectFolder }}/SmartRestaurant.Application.Tests/"
            runTestsInIsolation: true
            codeCoverageEnabled: true
        displayName: Run unittests