  parameters:
    WebProjectName: 'src/Presentation/SmartRestaurant.API/'
    TestProjectFolder: 'tests'
  
  jobs:
  - job: Build_the_API
    steps:
      - task: UseDotNet@2
        inputs:
          version: '3.1.410'
      - script: |
         cp devops/appsettings.json ${{ parameters.WebProjectName }}
         cd ${{ parameters.WebProjectName }}
         dotnet clean SmartRestaurant.API.csproj
         dotnet restore SmartRestaurant.API.csproj
        displayName: Restore Common Packages
      - script: |
         cp devops/appsettings.json src/Libraries/SmartRestaurant.Application/
         cp devops/appsettings.json src/Libraries/SmartRestaurant.Infrastructure/
         cd "src/Libraries/SmartRestaurant.Application/"
         dotnet add package DataTables.AspNetCore.Mvc
        displayName: Add AspNetCore.Mvc Packages
      - script: |
          cd ${{ parameters.WebProjectName }}
          dotnet build --no-restore SmartRestaurant.API.csproj
        displayName: Build
      
      
  - job: Database_Migration
    steps:
     - checkout: none
     - task: UseDotNet@2
        inputs:
          version: '3.1.410'
     - task: DotNetCoreCLI@2
       displayName: Install dotnet-ef
       inputs:
        command: 'custom'
        custom: 'tool'
        arguments: 'install --global dotnet-ef'
     - task: DotNetCoreCLI@2
       displayName: Check dotnet-ef version
       inputs:
        command: 'custom'
        custom: 'ef'
        arguments: '--version'
     - script: |
         cd ${{ parameters.WebProjectName }}
         dotnet ef database update --context:ApplicationDbContext
         dotnet ef database update --context:IdentityContext
       displayName: Database Initialization
    dependsOn: Build_the_API
    condition: succeeded()
