# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- develop

pool: 
  name: test-SmartRestaurant-agent
  workspace:
    clean: all

variables:
  WEB_PROJECT_NAME: "SmartRestaurant.Client.Web"
  ARTIFACTS_OUTPUT_PATH: "/home/gitlab-runner/SmartRestaurant"

steps:
- script: |
    cd "$WEB_PROJECT_NAME"
    dotnet clean
    dotnet restore
  displayName: Restore Nuget Packages
- script: |
    cd "SmartRestaurant.Application"
    dotnet add package DataTables.AspNetCore.Mvc
  displayName: Add AspNetCore.Mvc
- script: |
    cd "$WEB_PROJECT_NAME"
    dotnet build
  displayName: Build the Website
- script: dir
  workingDirectory: $(Agent.BuildDirectory)