

variables:
  - name: protectedBranche
    value: refs/heads/develop

stages:
- stage: Build_On_Dev_Evn
  condition: and(succeeded(), ne(variables['Build.SourceBranch'], 'refs/heads/develop'))
  pool: 
    name: features-SmartRestaurant-pool
    workspace:
      clean: all
  jobs:
  - template: devops/azure-build-template.yml

- stage: Deploy_To_Dev_Env
  dependsOn: Build_On_Dev_Evn
  condition: and(succeeded(), ne(variables['Build.SourceBranch'], 'refs/heads/develop'))
  pool: 
    name: features-SmartRestaurant-pool
    workspace:
      clean: none
  jobs:
  - template: devops/azure-deploy-template.yml
    parameters:
      envName: SmartRestaurant-Dev-Env


- stage: Build_On_Test_Evn
#  condition: and(succeeded(), eq(variables['Build.SourceBranchName'], 'develop'))
  pool: 
    name: test-SmartRestaurant-pool
    workspace:
      clean: all
  jobs:
  - template: devops/azure-build-template.yml

- stage: Deploy_To_Test_Env
  dependsOn: Build_On_Test_Evn
#  condition: and(succeeded(), eq(variables['Build.Reason'], 'PullRequest'))
#  condition: and(succeeded(), eq(variables['Build.SourceBranchName'], 'develop'))
  pool: 
    name: test-SmartRestaurant-pool
    workspace:
      clean: none
  jobs:
  - template: devops/azure-deploy-template.yml
    parameters:
      envName: SmartRestaurant-Test-Env

- stage: Build_On_Prod_Evn
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/release'))
  pool: 
    name: pre-prod-SmartRestaurant-pool
    workspace:
      clean: all
  jobs:
  - template: devops/azure-build-template.yml

- stage: Deploy_To_Prod_Env
  dependsOn: Build_On_Prod_Evn
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/release'))
  pool: 
    name: pre-prod-SmartRestaurant-pool
    workspace:
      clean: none
  jobs:
  - template: devops/azure-deploy-template.yml
    parameters:
      envName: SmartRestaurant-Prod-Env

- stage: Run_Tests
  dependsOn: []
  pool: 
    vmImage: 'windows-2019'
    workspace:
      clean: all
  jobs:
  - template: devops/azure-unittest-template.yml


#- stage: Run_Security_Tests
#  dependsOn: []
#  pool: 
#    vmImage: 'windows-2019'
#    workspace:
#      clean: all
#  jobs:
#  - template: devops/azure-security-template.yml
