stages:
- stage: Build_On_Test_Evn
  condition: and(succeeded(), ne(variables['Build.SourceBranch'], 'refs/heads/release'))
  pool: 
    name: test-SmartRestaurant-agent
    workspace:
      clean: all
  jobs:
  - template: devops/azure-build-template.yml

- stage: Deploy_To_Test_Env
  dependsOn: Build_On_Test_Evn
  condition: and(succeeded(), ne(variables['Build.SourceBranch'], 'refs/heads/release'))
  pool: 
    name: test-SmartRestaurant-agent
    workspace:
      clean: none
  jobs:
  - template: devops/azure-deploy-template.yml
    parameters:
      envName: SmartRestaurant-Test-Env


#- stage: Deploy_Angular_To_Test_Env
#  dependsOn: Deploy_To_Test_Env
#  condition: and(succeeded(), ne(variables['Build.SourceBranch'], 'refs/heads/release'))
#  pool: 
#    name: test-SmartRestaurant-agent
#    workspace:
#      clean: none
#  jobs:
#  - template: devops/azure-build-angular-template.yml
#    parameters:
#      envName: SmartRestaurant-Test-Env

- stage: Build_On_Prod_Evn
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/release'))
  pool: 
    name: prod-SmartRestaurant-pool
    workspace:
      clean: all
  jobs:
  - template: devops/azure-build-template.yml

- stage: Deploy_To_Prod_Env
  dependsOn: Build_On_Prod_Evn
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/release'))
  pool: 
    name: prod-SmartRestaurant-pool
    workspace:
      clean: none
  jobs:
  - template: devops/azure-deploy-template.yml
    parameters:
      envName: SmartRestaurant-Prod-Env

- stage: Run_Tests
  dependsOn: []
  pool: 
    vmImage: 'windows-2019'
    workspace:
      clean: all
  jobs:
  - template: devops/azure-unittest-template.yml

#- stage: Deploy_Angular_To_Prod_Env
#  dependsOn: Deploy_To_Prod_Env
#  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/release'))
#  pool: 
#    name: prod-SmartRestaurant-pool
#    workspace:
#      clean: none
#  jobs:
#  - template: devops/azure-build-angular-template.yml
#    parameters:
#      envName: SmartRestaurant-Prod-Env