stages:
- stage: APK_On_Test_Evn
  condition: and(succeeded(), ne(variables['Build.SourceBranch'], 'refs/heads/release'))
  pool: 
    vmImage: 'vs2017-win2016'
    workspace:
      clean: all
  jobs:
  - job:
    steps:
    - task: DotNetCoreCLI@2
      displayName: "NuGet Restore"
      inputs:
        command: restore
        projects: '**/*.csproj'
    - task: DotNetCoreCLI@2
      displayName: "Build APK"
      inputs:
        command: build
        projects: 'SmartRestaurant.Forms/SRMobile.Android/SmartRestaurant.Diner.Android.csproj'
        arguments: '--configuration Release'