stages:
- stage: Build_and_DB_Migration
  condition: and(succeeded(), ne(variables['Build.SourceBranch'], 'refs/heads/release'))
  pool: 
    name: test-SmartRestaurant-agent
    workspace:
      clean: all
  jobs:
  - template: devops/azure-build-template.yml
  
- stage: Deployment
  dependsOn: Build_and_DB_Migration
  condition: and(succeeded(), ne(variables['Build.SourceBranch'], 'refs/heads/release'))
  pool: 
    name: test-SmartRestaurant-agent
    workspace:
      clean: none
  jobs:
  - template: devops/azure-deploy-template.yml
    parameters:
      envName: SmartRestaurant-Test-Env