stages:
- stage: APK_On_Test_Evn
  condition: and(succeeded(), ne(variables['Build.SourceBranch'], 'refs/heads/release'))
  pool: 
    vmImage: 'vs2017-win2016'
    demands:
      - MSBuild
      - Xamarin.Android
      - JDK
    workspace:
      clean: all

  jobs:
  - job:
    steps:
    - task: NuGetToolInstaller@0
    - task: NuGetCommand@2
      inputs:
        restoreSolution: 'SmartRestaurant.Forms/SRMobile.Android/SmartRestaurant.Diner.Android.csproj'
    - task: XamarinAndroid@1
      inputs:
        projectFile: 'SmartRestaurant.Forms/SRMobile.Android/SmartRestaurant.Diner.Android.csproj'
        outputDirectory: '$(build.binariesDirectory)/Release'
        configuration: 'Release'