// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SmartRestaurant.Infrastructure.Persistence;

namespace SmartRestaurant.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20210712183242_updateSeedData_03")]
    partial class updateSeedData_03
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SmartRestaurant.Domain.Entities.FoodBusiness", b =>
                {
                    b.Property<Guid>("FoodBusinessId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("AcceptTakeout")
                        .HasColumnType("bit");

                    b.Property<bool>("AcceptsCreditCards")
                        .HasColumnType("bit");

                    b.Property<double>("AverageRating")
                        .HasColumnType("float");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FoodBusinessAdministratorId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FoodBusinessCategory")
                        .HasColumnType("int");

                    b.Property<int>("FoodBusinessState")
                        .HasColumnType("int");

                    b.Property<bool>("HasCarParking")
                        .HasColumnType("bit");

                    b.Property<bool>("IsHandicapFriendly")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NIF")
                        .HasColumnType("int");

                    b.Property<int>("NIS")
                        .HasColumnType("int");

                    b.Property<int>("NRC")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NumberRatings")
                        .HasColumnType("int");

                    b.Property<bool>("OffersTakeout")
                        .HasColumnType("bit");

                    b.Property<string>("Tags")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Website")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("FoodBusinessId");

                    b.ToTable("FoodBusinesses");

                    b.HasData(
                        new
                        {
                            FoodBusinessId = new Guid("3cbf3570-4444-4673-8746-29b7cf568093"),
                            AcceptTakeout = true,
                            AcceptsCreditCards = true,
                            AverageRating = 4.0,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "",
                            FoodBusinessAdministratorId = "3cbf3570-4444-4444-8746-29b7cf568093",
                            FoodBusinessCategory = 0,
                            FoodBusinessState = 0,
                            HasCarParking = true,
                            IsHandicapFriendly = true,
                            LastModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NIF = 0,
                            NIS = 0,
                            NRC = 0,
                            Name = "Taj mahal",
                            NumberRatings = 0,
                            OffersTakeout = true,
                            Tags = "",
                            Website = ""
                        },
                        new
                        {
                            FoodBusinessId = new Guid("66bf3570-440d-4673-8746-29b7cf568099"),
                            AcceptTakeout = true,
                            AcceptsCreditCards = true,
                            AverageRating = 4.0,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "",
                            FoodBusinessAdministratorId = "44bf3570-0d44-4673-8746-29b7cf568088",
                            FoodBusinessCategory = 0,
                            FoodBusinessState = 0,
                            HasCarParking = true,
                            IsHandicapFriendly = true,
                            LastModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NIF = 0,
                            NIS = 0,
                            NRC = 0,
                            Name = "Mcdonald's",
                            NumberRatings = 0,
                            OffersTakeout = true,
                            Tags = "",
                            Website = ""
                        });
                });

            modelBuilder.Entity("SmartRestaurant.Domain.Entities.FoodBusinessImage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("ImageBytes")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("ImageTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsLogo")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("FoodBusinessImages");
                });

            modelBuilder.Entity("SmartRestaurant.Domain.Entities.FoodBusinessUser", b =>
                {
                    b.Property<string>("ApplicationUserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid>("FoodBusinessId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ApplicationUserId", "FoodBusinessId");

                    b.HasIndex("FoodBusinessId");

                    b.ToTable("FoodBusinessUsers");
                });

            modelBuilder.Entity("SmartRestaurant.Domain.Entities.Menu", b =>
                {
                    b.Property<Guid>("MenuId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("FoodBusinessId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("LastModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MenuState")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MenuId");

                    b.HasIndex("FoodBusinessId");

                    b.ToTable("Menus");
                });

            modelBuilder.Entity("SmartRestaurant.Domain.Entities.Reservation", b =>
                {
                    b.Property<Guid>("ReservationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatorType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("FoodBusinessId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("LastModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NumberOfDiners")
                        .HasColumnType("int");

                    b.Property<DateTime>("ReservationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ReservationName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ReservationId");

                    b.HasIndex("FoodBusinessId");

                    b.ToTable("Reservations");

                    b.HasData(
                        new
                        {
                            ReservationId = new Guid("acbf657b-3398-7a73-8746-77b7cf596300"),
                            CreatedAt = new DateTime(2021, 7, 12, 19, 32, 41, 409, DateTimeKind.Local).AddTicks(8110),
                            CreatedBy = "5a84cd00-59f0-4b22-bfce-07c080829118",
                            CreatorType = "Diner",
                            FoodBusinessId = new Guid("3cbf3570-4444-4673-8746-29b7cf568093"),
                            LastModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NumberOfDiners = 2,
                            ReservationDate = new DateTime(2021, 7, 13, 0, 32, 41, 406, DateTimeKind.Local).AddTicks(6278),
                            ReservationName = "ReservationName_00"
                        },
                        new
                        {
                            ReservationId = new Guid("acbf657b-3398-7a73-8746-77b7cf596301"),
                            CreatedAt = new DateTime(2021, 7, 13, 0, 32, 41, 410, DateTimeKind.Local).AddTicks(691),
                            CreatedBy = "5a84cd00-59f0-4b22-bfce-07c080829118",
                            CreatorType = "Diner",
                            FoodBusinessId = new Guid("66bf3570-440d-4673-8746-29b7cf568099"),
                            LastModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NumberOfDiners = 5,
                            ReservationDate = new DateTime(2021, 7, 13, 3, 32, 41, 410, DateTimeKind.Local).AddTicks(573),
                            ReservationName = "ReservationName_01"
                        },
                        new
                        {
                            ReservationId = new Guid("acbf657b-3398-7a73-8746-77b7cf596302"),
                            CreatedAt = new DateTime(2021, 6, 27, 19, 32, 41, 410, DateTimeKind.Local).AddTicks(791),
                            CreatedBy = "5a84cd00-59f0-4b22-bfce-07c080829118",
                            CreatorType = "Diner",
                            FoodBusinessId = new Guid("3cbf3570-4444-4673-8746-29b7cf568093"),
                            LastModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NumberOfDiners = 3,
                            ReservationDate = new DateTime(2021, 7, 13, 19, 32, 41, 410, DateTimeKind.Local).AddTicks(735),
                            ReservationName = "ReservationName_02"
                        },
                        new
                        {
                            ReservationId = new Guid("acbf657b-3398-7a73-8746-77b7cf596303"),
                            CreatedAt = new DateTime(2021, 7, 27, 19, 32, 41, 410, DateTimeKind.Local).AddTicks(930),
                            CreatedBy = "5a84cd00-59f0-4b22-bfce-07c080829118",
                            CreatorType = "Diner",
                            FoodBusinessId = new Guid("66bf3570-440d-4673-8746-29b7cf568099"),
                            LastModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NumberOfDiners = 2,
                            ReservationDate = new DateTime(2026, 7, 12, 19, 32, 41, 410, DateTimeKind.Local).AddTicks(802),
                            ReservationName = "ReservationName_03"
                        },
                        new
                        {
                            ReservationId = new Guid("acbf657b-3398-7a73-8746-77b7cf596304"),
                            CreatedAt = new DateTime(2021, 7, 12, 20, 8, 41, 410, DateTimeKind.Local).AddTicks(955),
                            CreatedBy = "5a84cd00-59f0-4b22-bfce-07c080829118",
                            CreatorType = "Diner",
                            FoodBusinessId = new Guid("3cbf3570-4444-4673-8746-29b7cf568093"),
                            LastModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NumberOfDiners = 8,
                            ReservationDate = new DateTime(2036, 7, 12, 19, 32, 41, 410, DateTimeKind.Local).AddTicks(945),
                            ReservationName = "ReservationName_04"
                        },
                        new
                        {
                            ReservationId = new Guid("acbf657b-3398-7a73-8746-77b7cf596305"),
                            CreatedAt = new DateTime(2021, 7, 11, 19, 32, 41, 410, DateTimeKind.Local).AddTicks(989),
                            CreatedBy = "5a84cd00-59f0-4b22-bfce-07c080829118",
                            CreatorType = "Diner",
                            FoodBusinessId = new Guid("66bf3570-440d-4673-8746-29b7cf568099"),
                            LastModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NumberOfDiners = 13,
                            ReservationDate = new DateTime(2021, 7, 12, 16, 32, 41, 410, DateTimeKind.Local).AddTicks(986),
                            ReservationName = "ReservationName_05"
                        },
                        new
                        {
                            ReservationId = new Guid("acbf657b-3398-7a73-8746-77b7cf596306"),
                            CreatedAt = new DateTime(2021, 6, 12, 19, 32, 41, 410, DateTimeKind.Local).AddTicks(999),
                            CreatedBy = "5a84cd00-59f0-4b22-bfce-07c080829118",
                            CreatorType = "Diner",
                            FoodBusinessId = new Guid("3cbf3570-4444-4673-8746-29b7cf568093"),
                            LastModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NumberOfDiners = 7,
                            ReservationDate = new DateTime(2021, 6, 30, 19, 32, 41, 410, DateTimeKind.Local).AddTicks(997),
                            ReservationName = "ReservationName_06"
                        },
                        new
                        {
                            ReservationId = new Guid("acbf657b-3398-7a73-8746-77b7cf596307"),
                            CreatedAt = new DateTime(2021, 5, 12, 19, 32, 41, 410, DateTimeKind.Local).AddTicks(1012),
                            CreatedBy = "5a84cd00-59f0-4b22-bfce-07c080829118",
                            CreatorType = "Diner",
                            FoodBusinessId = new Guid("3cbf3570-4444-4673-8746-29b7cf568093"),
                            LastModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NumberOfDiners = 9,
                            ReservationDate = new DateTime(2021, 5, 20, 19, 32, 41, 410, DateTimeKind.Local).AddTicks(1009),
                            ReservationName = "ReservationName_07"
                        },
                        new
                        {
                            ReservationId = new Guid("acbf657b-3398-7a73-8746-77b7cf596308"),
                            CreatedAt = new DateTime(2021, 11, 12, 19, 32, 41, 410, DateTimeKind.Local).AddTicks(1025),
                            CreatedBy = "5a84cd00-59f0-4b22-bfce-07c080829118",
                            CreatorType = "Diner",
                            FoodBusinessId = new Guid("3cbf3570-4444-4673-8746-29b7cf568093"),
                            LastModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NumberOfDiners = 4,
                            ReservationDate = new DateTime(2021, 12, 12, 19, 32, 41, 410, DateTimeKind.Local).AddTicks(1023),
                            ReservationName = "ReservationName_08"
                        },
                        new
                        {
                            ReservationId = new Guid("acbf657b-3398-7a73-8746-77b7cf596309"),
                            CreatedAt = new DateTime(2021, 7, 12, 19, 32, 41, 410, DateTimeKind.Local).AddTicks(1037),
                            CreatedBy = "6b14cd00-59f0-4422-bfce-07c080829987",
                            CreatorType = "Diner",
                            FoodBusinessId = new Guid("3cbf3570-4444-4673-8746-29b7cf568093"),
                            LastModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NumberOfDiners = 3,
                            ReservationDate = new DateTime(2021, 7, 12, 23, 32, 41, 410, DateTimeKind.Local).AddTicks(1035),
                            ReservationName = "ReservationName_09"
                        },
                        new
                        {
                            ReservationId = new Guid("acbf657b-3398-7a73-8746-77b7cf596310"),
                            CreatedAt = new DateTime(2021, 7, 13, 0, 32, 41, 410, DateTimeKind.Local).AddTicks(1047),
                            CreatedBy = "6b14cd00-59f0-4422-bfce-07c080829987",
                            CreatorType = "Diner",
                            FoodBusinessId = new Guid("66bf3570-440d-4673-8746-29b7cf568099"),
                            LastModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NumberOfDiners = 6,
                            ReservationDate = new DateTime(2021, 7, 13, 2, 32, 41, 410, DateTimeKind.Local).AddTicks(1045),
                            ReservationName = "ReservationName_10"
                        },
                        new
                        {
                            ReservationId = new Guid("acbf657b-3398-7a73-8746-77b7cf596311"),
                            CreatedAt = new DateTime(2021, 6, 28, 19, 32, 41, 410, DateTimeKind.Local).AddTicks(1268),
                            CreatedBy = "6b14cd00-59f0-4422-bfce-07c080829987",
                            CreatorType = "Diner",
                            FoodBusinessId = new Guid("3cbf3570-4444-4673-8746-29b7cf568093"),
                            LastModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NumberOfDiners = 4,
                            ReservationDate = new DateTime(2021, 7, 14, 19, 32, 41, 410, DateTimeKind.Local).AddTicks(1263),
                            ReservationName = "ReservationName_11"
                        },
                        new
                        {
                            ReservationId = new Guid("acbf657b-3398-7a73-8746-77b7cf596312"),
                            CreatedAt = new DateTime(2021, 9, 1, 19, 32, 41, 410, DateTimeKind.Local).AddTicks(1281),
                            CreatedBy = "6b14cd00-59f0-4422-bfce-07c080829987",
                            CreatorType = "Diner",
                            FoodBusinessId = new Guid("66bf3570-440d-4673-8746-29b7cf568099"),
                            LastModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NumberOfDiners = 3,
                            ReservationDate = new DateTime(2025, 7, 12, 19, 32, 41, 410, DateTimeKind.Local).AddTicks(1277),
                            ReservationName = "ReservationName_12"
                        },
                        new
                        {
                            ReservationId = new Guid("acbf657b-3398-7a73-8746-77b7cf596313"),
                            CreatedAt = new DateTime(2021, 7, 12, 20, 8, 41, 410, DateTimeKind.Local).AddTicks(1293),
                            CreatedBy = "6b14cd00-59f0-4422-bfce-07c080829987",
                            CreatorType = "Diner",
                            FoodBusinessId = new Guid("3cbf3570-4444-4673-8746-29b7cf568093"),
                            LastModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NumberOfDiners = 9,
                            ReservationDate = new DateTime(2036, 7, 12, 19, 32, 41, 410, DateTimeKind.Local).AddTicks(1289),
                            ReservationName = "ReservationName_13"
                        },
                        new
                        {
                            ReservationId = new Guid("acbf657b-3398-7a73-8746-77b7cf596314"),
                            CreatedAt = new DateTime(2021, 7, 10, 19, 32, 41, 410, DateTimeKind.Local).AddTicks(1304),
                            CreatedBy = "6b14cd00-59f0-4422-bfce-07c080829987",
                            CreatorType = "Diner",
                            FoodBusinessId = new Guid("66bf3570-440d-4673-8746-29b7cf568099"),
                            LastModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NumberOfDiners = 14,
                            ReservationDate = new DateTime(2021, 7, 12, 15, 32, 41, 410, DateTimeKind.Local).AddTicks(1301),
                            ReservationName = "ReservationName_14"
                        },
                        new
                        {
                            ReservationId = new Guid("acbf657b-3398-7a73-8746-77b7cf596315"),
                            CreatedAt = new DateTime(2021, 6, 12, 19, 32, 41, 410, DateTimeKind.Local).AddTicks(1314),
                            CreatedBy = "6b14cd00-59f0-4422-bfce-07c080829987",
                            CreatorType = "Diner",
                            FoodBusinessId = new Guid("3cbf3570-4444-4673-8746-29b7cf568093"),
                            LastModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NumberOfDiners = 8,
                            ReservationDate = new DateTime(2021, 6, 29, 19, 32, 41, 410, DateTimeKind.Local).AddTicks(1312),
                            ReservationName = "ReservationName_15"
                        },
                        new
                        {
                            ReservationId = new Guid("acbf657b-3398-7a73-8746-77b7cf596316"),
                            CreatedAt = new DateTime(2021, 4, 12, 19, 32, 41, 410, DateTimeKind.Local).AddTicks(1325),
                            CreatedBy = "6b14cd00-59f0-4422-bfce-07c080829987",
                            CreatorType = "Diner",
                            FoodBusinessId = new Guid("3cbf3570-4444-4673-8746-29b7cf568093"),
                            LastModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NumberOfDiners = 10,
                            ReservationDate = new DateTime(2021, 5, 23, 19, 32, 41, 410, DateTimeKind.Local).AddTicks(1323),
                            ReservationName = "ReservationName_16"
                        },
                        new
                        {
                            ReservationId = new Guid("acbf657b-3398-7a73-8746-77b7cf596317"),
                            CreatedAt = new DateTime(2021, 10, 12, 19, 32, 41, 410, DateTimeKind.Local).AddTicks(1338),
                            CreatedBy = "6b14cd00-59f0-4422-bfce-07c080829987",
                            CreatorType = "Diner",
                            FoodBusinessId = new Guid("3cbf3570-4444-4673-8746-29b7cf568093"),
                            LastModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NumberOfDiners = 5,
                            ReservationDate = new DateTime(2021, 11, 12, 19, 32, 41, 410, DateTimeKind.Local).AddTicks(1336),
                            ReservationName = "ReservationName_17"
                        },
                        new
                        {
                            ReservationId = new Guid("acbf657b-3398-7a73-8746-77b7cf596327"),
                            CreatedAt = new DateTime(2021, 7, 12, 19, 32, 41, 410, DateTimeKind.Local).AddTicks(1352),
                            CreatedBy = "a1997466-cedc-4850-b18d-0ac4f4102cff",
                            CreatorType = "FoodBusinessManager",
                            FoodBusinessId = new Guid("3cbf3570-4444-4673-8746-29b7cf568093"),
                            LastModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NumberOfDiners = 3,
                            ReservationDate = new DateTime(2021, 7, 12, 22, 32, 41, 410, DateTimeKind.Local).AddTicks(1350),
                            ReservationName = "ReservationName_27"
                        },
                        new
                        {
                            ReservationId = new Guid("acbf657b-3398-7a73-8746-77b7cf596328"),
                            CreatedAt = new DateTime(2021, 7, 12, 23, 32, 41, 410, DateTimeKind.Local).AddTicks(1362),
                            CreatedBy = "a1997466-cedc-4850-b18d-0ac4f4102cff",
                            CreatorType = "FoodBusinessManager",
                            FoodBusinessId = new Guid("3cbf3570-4444-4673-8746-29b7cf568093"),
                            LastModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NumberOfDiners = 6,
                            ReservationDate = new DateTime(2021, 7, 13, 1, 32, 41, 410, DateTimeKind.Local).AddTicks(1360),
                            ReservationName = "ReservationName_28"
                        },
                        new
                        {
                            ReservationId = new Guid("acbf657b-3398-7a73-8746-77b7cf596329"),
                            CreatedAt = new DateTime(2021, 6, 28, 19, 32, 41, 410, DateTimeKind.Local).AddTicks(1371),
                            CreatedBy = "a1997466-cedc-4850-b18d-0ac4f4102cff",
                            CreatorType = "FoodBusinessManager",
                            FoodBusinessId = new Guid("3cbf3570-4444-4673-8746-29b7cf568093"),
                            LastModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NumberOfDiners = 4,
                            ReservationDate = new DateTime(2021, 7, 13, 19, 32, 41, 410, DateTimeKind.Local).AddTicks(1369),
                            ReservationName = "ReservationName_29"
                        },
                        new
                        {
                            ReservationId = new Guid("acbf657b-3398-7a73-8746-77b7cf596330"),
                            CreatedAt = new DateTime(2021, 9, 5, 19, 32, 41, 410, DateTimeKind.Local).AddTicks(1382),
                            CreatedBy = "a1997466-cedc-4850-b18d-0ac4f4102cff",
                            CreatorType = "FoodBusinessManager",
                            FoodBusinessId = new Guid("3cbf3570-4444-4673-8746-29b7cf568093"),
                            LastModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NumberOfDiners = 3,
                            ReservationDate = new DateTime(2024, 7, 12, 19, 32, 41, 410, DateTimeKind.Local).AddTicks(1379),
                            ReservationName = "ReservationName_30"
                        },
                        new
                        {
                            ReservationId = new Guid("acbf657b-3398-7a73-8746-77b7cf596331"),
                            CreatedAt = new DateTime(2021, 7, 12, 19, 47, 41, 410, DateTimeKind.Local).AddTicks(1393),
                            CreatedBy = "a1997466-cedc-4850-b18d-0ac4f4102cff",
                            CreatorType = "FoodBusinessManager",
                            FoodBusinessId = new Guid("3cbf3570-4444-4673-8746-29b7cf568093"),
                            LastModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NumberOfDiners = 9,
                            ReservationDate = new DateTime(2034, 7, 12, 19, 32, 41, 410, DateTimeKind.Local).AddTicks(1390),
                            ReservationName = "ReservationName_31"
                        },
                        new
                        {
                            ReservationId = new Guid("acbf657b-3398-7a73-8746-77b7cf596332"),
                            CreatedAt = new DateTime(2021, 7, 9, 19, 32, 41, 410, DateTimeKind.Local).AddTicks(1402),
                            CreatedBy = "a1997466-cedc-4850-b18d-0ac4f4102cff",
                            CreatorType = "FoodBusinessManager",
                            FoodBusinessId = new Guid("3cbf3570-4444-4673-8746-29b7cf568093"),
                            LastModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NumberOfDiners = 14,
                            ReservationDate = new DateTime(2021, 7, 12, 16, 32, 41, 410, DateTimeKind.Local).AddTicks(1400),
                            ReservationName = "ReservationName_32"
                        },
                        new
                        {
                            ReservationId = new Guid("acbf657b-3398-7a73-8746-77b7cf596333"),
                            CreatedAt = new DateTime(2021, 6, 12, 19, 32, 41, 410, DateTimeKind.Local).AddTicks(1412),
                            CreatedBy = "a1997466-cedc-4850-b18d-0ac4f4102cff",
                            CreatorType = "FoodBusinessManager",
                            FoodBusinessId = new Guid("3cbf3570-4444-4673-8746-29b7cf568093"),
                            LastModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NumberOfDiners = 8,
                            ReservationDate = new DateTime(2021, 7, 2, 19, 32, 41, 410, DateTimeKind.Local).AddTicks(1410),
                            ReservationName = "ReservationName_33"
                        },
                        new
                        {
                            ReservationId = new Guid("acbf657b-3398-7a73-8746-77b7cf596334"),
                            CreatedAt = new DateTime(2021, 5, 12, 19, 32, 41, 410, DateTimeKind.Local).AddTicks(1421),
                            CreatedBy = "a1997466-cedc-4850-b18d-0ac4f4102cff",
                            CreatorType = "FoodBusinessManager",
                            FoodBusinessId = new Guid("3cbf3570-4444-4673-8746-29b7cf568093"),
                            LastModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NumberOfDiners = 10,
                            ReservationDate = new DateTime(2021, 5, 30, 19, 32, 41, 410, DateTimeKind.Local).AddTicks(1419),
                            ReservationName = "ReservationName_34"
                        },
                        new
                        {
                            ReservationId = new Guid("acbf657b-3398-7a73-8746-77b7cf596335"),
                            CreatedAt = new DateTime(2021, 9, 12, 19, 32, 41, 410, DateTimeKind.Local).AddTicks(1434),
                            CreatedBy = "a1997466-cedc-4850-b18d-0ac4f4102cff",
                            CreatorType = "FoodBusinessManager",
                            FoodBusinessId = new Guid("3cbf3570-4444-4673-8746-29b7cf568093"),
                            LastModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NumberOfDiners = 5,
                            ReservationDate = new DateTime(2021, 10, 12, 19, 32, 41, 410, DateTimeKind.Local).AddTicks(1431),
                            ReservationName = "ReservationName_35"
                        },
                        new
                        {
                            ReservationId = new Guid("acbf657b-3398-7a73-8746-77b7cf596336"),
                            CreatedAt = new DateTime(2021, 7, 12, 19, 32, 41, 410, DateTimeKind.Local).AddTicks(1444),
                            CreatedBy = "b2207466-ceda-4b50-b18d-0ac4f4102caa",
                            CreatorType = "FoodBusinessManager",
                            FoodBusinessId = new Guid("66bf3570-440d-4673-8746-29b7cf568099"),
                            LastModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NumberOfDiners = 4,
                            ReservationDate = new DateTime(2021, 7, 12, 20, 32, 41, 410, DateTimeKind.Local).AddTicks(1442),
                            ReservationName = "ReservationName_36"
                        },
                        new
                        {
                            ReservationId = new Guid("acbf657b-3398-7a73-8746-77b7cf596337"),
                            CreatedAt = new DateTime(2021, 7, 12, 21, 32, 41, 410, DateTimeKind.Local).AddTicks(1454),
                            CreatedBy = "b2207466-ceda-4b50-b18d-0ac4f4102caa",
                            CreatorType = "FoodBusinessManager",
                            FoodBusinessId = new Guid("66bf3570-440d-4673-8746-29b7cf568099"),
                            LastModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NumberOfDiners = 5,
                            ReservationDate = new DateTime(2021, 7, 12, 23, 32, 41, 410, DateTimeKind.Local).AddTicks(1452),
                            ReservationName = "ReservationName_37"
                        },
                        new
                        {
                            ReservationId = new Guid("acbf657b-3398-7a73-8746-77b7cf596338"),
                            CreatedAt = new DateTime(2021, 6, 28, 19, 32, 41, 410, DateTimeKind.Local).AddTicks(1465),
                            CreatedBy = "b2207466-ceda-4b50-b18d-0ac4f4102caa",
                            CreatorType = "FoodBusinessManager",
                            FoodBusinessId = new Guid("66bf3570-440d-4673-8746-29b7cf568099"),
                            LastModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NumberOfDiners = 6,
                            ReservationDate = new DateTime(2021, 7, 17, 19, 32, 41, 410, DateTimeKind.Local).AddTicks(1463),
                            ReservationName = "ReservationName_38"
                        },
                        new
                        {
                            ReservationId = new Guid("acbf657b-3398-7a73-8746-77b7cf596339"),
                            CreatedAt = new DateTime(2021, 8, 1, 19, 32, 41, 410, DateTimeKind.Local).AddTicks(1475),
                            CreatedBy = "b2207466-ceda-4b50-b18d-0ac4f4102caa",
                            CreatorType = "FoodBusinessManager",
                            FoodBusinessId = new Guid("66bf3570-440d-4673-8746-29b7cf568099"),
                            LastModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NumberOfDiners = 7,
                            ReservationDate = new DateTime(2023, 7, 12, 19, 32, 41, 410, DateTimeKind.Local).AddTicks(1473),
                            ReservationName = "ReservationName_39"
                        },
                        new
                        {
                            ReservationId = new Guid("acbf657b-3398-7a73-8746-77b7cf596340"),
                            CreatedAt = new DateTime(2021, 7, 12, 20, 15, 41, 410, DateTimeKind.Local).AddTicks(1485),
                            CreatedBy = "b2207466-ceda-4b50-b18d-0ac4f4102caa",
                            CreatorType = "FoodBusinessManager",
                            FoodBusinessId = new Guid("66bf3570-440d-4673-8746-29b7cf568099"),
                            LastModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NumberOfDiners = 10,
                            ReservationDate = new DateTime(2031, 7, 12, 19, 32, 41, 410, DateTimeKind.Local).AddTicks(1483),
                            ReservationName = "ReservationName_40"
                        },
                        new
                        {
                            ReservationId = new Guid("acbf657b-3398-7a73-8746-77b7cf596341"),
                            CreatedAt = new DateTime(2021, 7, 7, 19, 32, 41, 410, DateTimeKind.Local).AddTicks(1495),
                            CreatedBy = "b2207466-ceda-4b50-b18d-0ac4f4102caa",
                            CreatorType = "FoodBusinessManager",
                            FoodBusinessId = new Guid("66bf3570-440d-4673-8746-29b7cf568099"),
                            LastModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NumberOfDiners = 17,
                            ReservationDate = new DateTime(2021, 7, 12, 7, 32, 41, 410, DateTimeKind.Local).AddTicks(1493),
                            ReservationName = "ReservationName_41"
                        },
                        new
                        {
                            ReservationId = new Guid("acbf657b-3398-7a73-8746-77b7cf596342"),
                            CreatedAt = new DateTime(2021, 6, 12, 19, 32, 41, 410, DateTimeKind.Local).AddTicks(1504),
                            CreatedBy = "b2207466-ceda-4b50-b18d-0ac4f4102caa",
                            CreatorType = "FoodBusinessManager",
                            FoodBusinessId = new Guid("66bf3570-440d-4673-8746-29b7cf568099"),
                            LastModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NumberOfDiners = 4,
                            ReservationDate = new DateTime(2021, 7, 5, 19, 32, 41, 410, DateTimeKind.Local).AddTicks(1502),
                            ReservationName = "ReservationName_42"
                        },
                        new
                        {
                            ReservationId = new Guid("acbf657b-3398-7a73-8746-77b7cf596343"),
                            CreatedAt = new DateTime(2021, 8, 12, 19, 32, 41, 410, DateTimeKind.Local).AddTicks(1514),
                            CreatedBy = "b2207466-ceda-4b50-b18d-0ac4f4102caa",
                            CreatorType = "FoodBusinessManager",
                            FoodBusinessId = new Guid("66bf3570-440d-4673-8746-29b7cf568099"),
                            LastModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NumberOfDiners = 11,
                            ReservationDate = new DateTime(2021, 8, 24, 19, 32, 41, 410, DateTimeKind.Local).AddTicks(1512),
                            ReservationName = "ReservationName_43"
                        },
                        new
                        {
                            ReservationId = new Guid("acbf657b-3398-7a73-8746-77b7cf596344"),
                            CreatedAt = new DateTime(2021, 9, 12, 19, 32, 41, 410, DateTimeKind.Local).AddTicks(1526),
                            CreatedBy = "b2207466-ceda-4b50-b18d-0ac4f4102caa",
                            CreatorType = "FoodBusinessManager",
                            FoodBusinessId = new Guid("66bf3570-440d-4673-8746-29b7cf568099"),
                            LastModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NumberOfDiners = 2,
                            ReservationDate = new DateTime(2021, 10, 12, 19, 32, 41, 410, DateTimeKind.Local).AddTicks(1523),
                            ReservationName = "ReservationName_44"
                        });
                });

            modelBuilder.Entity("SmartRestaurant.Domain.Entities.Section", b =>
                {
                    b.Property<Guid>("SectionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("MenuId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SectionId");

                    b.HasIndex("MenuId");

                    b.ToTable("Sections");
                });

            modelBuilder.Entity("SmartRestaurant.Domain.Entities.SubSection", b =>
                {
                    b.Property<Guid>("SubSectionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("SectionId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("SubSectionId");

                    b.HasIndex("SectionId");

                    b.ToTable("SubSections");
                });

            modelBuilder.Entity("SmartRestaurant.Domain.Entities.Table", b =>
                {
                    b.Property<Guid>("TableId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TableNumber")
                        .HasColumnType("int");

                    b.Property<short>("TableState")
                        .HasColumnType("smallint");

                    b.Property<Guid>("ZoneId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("TableId");

                    b.HasIndex("ZoneId");

                    b.ToTable("Tables");
                });

            modelBuilder.Entity("SmartRestaurant.Domain.Entities.Zone", b =>
                {
                    b.Property<Guid>("ZoneId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("FoodBusinessId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("LastModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ZoneTitle")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ZoneId");

                    b.HasIndex("FoodBusinessId");

                    b.ToTable("Zones");
                });

            modelBuilder.Entity("SmartRestaurant.Domain.Entities.FoodBusiness", b =>
                {
                    b.OwnsOne("SmartRestaurant.Domain.ValueObjects.Address", "Address", b1 =>
                        {
                            b1.Property<Guid>("FoodBusinessId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("City")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Country")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("StreetAddress")
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("FoodBusinessId");

                            b1.ToTable("FoodBusinesses");

                            b1.WithOwner()
                                .HasForeignKey("FoodBusinessId");

                            b1.OwnsOne("SmartRestaurant.Domain.ValueObjects.GeoPosition", "GeoPosition", b2 =>
                                {
                                    b2.Property<Guid>("AddressFoodBusinessId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<string>("Latitude")
                                        .HasColumnType("nvarchar(max)");

                                    b2.Property<string>("Longitude")
                                        .HasColumnType("nvarchar(max)");

                                    b2.HasKey("AddressFoodBusinessId");

                                    b2.ToTable("FoodBusinesses");

                                    b2.WithOwner()
                                        .HasForeignKey("AddressFoodBusinessId");
                                });
                        });

                    b.OwnsOne("SmartRestaurant.Domain.ValueObjects.PhoneNumber", "PhoneNumber", b1 =>
                        {
                            b1.Property<Guid>("FoodBusinessId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("CountryCode")
                                .HasColumnType("int");

                            b1.Property<int>("Number")
                                .HasColumnType("int");

                            b1.HasKey("FoodBusinessId");

                            b1.ToTable("FoodBusinesses");

                            b1.WithOwner()
                                .HasForeignKey("FoodBusinessId");
                        });
                });

            modelBuilder.Entity("SmartRestaurant.Domain.Entities.FoodBusinessUser", b =>
                {
                    b.HasOne("SmartRestaurant.Domain.Entities.FoodBusiness", "FoodBusiness")
                        .WithMany()
                        .HasForeignKey("FoodBusinessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SmartRestaurant.Domain.Entities.Menu", b =>
                {
                    b.HasOne("SmartRestaurant.Domain.Entities.FoodBusiness", "FoodBusiness")
                        .WithMany()
                        .HasForeignKey("FoodBusinessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SmartRestaurant.Domain.Entities.Reservation", b =>
                {
                    b.HasOne("SmartRestaurant.Domain.Entities.FoodBusiness", "FoodBusiness")
                        .WithMany()
                        .HasForeignKey("FoodBusinessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SmartRestaurant.Domain.Entities.Section", b =>
                {
                    b.HasOne("SmartRestaurant.Domain.Entities.Menu", "Menu")
                        .WithMany()
                        .HasForeignKey("MenuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SmartRestaurant.Domain.Entities.SubSection", b =>
                {
                    b.HasOne("SmartRestaurant.Domain.Entities.Section", "Section")
                        .WithMany()
                        .HasForeignKey("SectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SmartRestaurant.Domain.Entities.Table", b =>
                {
                    b.HasOne("SmartRestaurant.Domain.Entities.Zone", "Zone")
                        .WithMany()
                        .HasForeignKey("ZoneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SmartRestaurant.Domain.Entities.Zone", b =>
                {
                    b.HasOne("SmartRestaurant.Domain.Entities.FoodBusiness", "FoodBusiness")
                        .WithMany()
                        .HasForeignKey("FoodBusinessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
